image: Visual Studio 2015

platform:
  - x64

clone_folder: c:\mazoea\installation\te-external

environment:
  my_var1: value1

matrix:
  fast_finish: true

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - xcopy /S /I _vsprops-base ..\cpp-template\projects\vsprops-base
  - python create_links.py
  - cd ..
  - git clone --depth=1 https://github.com/mazoea/te-builder.git te-builder
  - cd te-builder\src
  - python main.py --settings=externals_only.json

build_script:
  - mkdir build
